apiVersion: v1
kind: ConfigMap
metadata:
  name: migration-common-config
  namespace: db-migration
data:
  AZURE_SERVER_BASE_NAME: "migration-demo-raghava"
  AZURE_SERVER_FULL: "migration-demo-raghava-20251006164232.postgres.database.azure.com"
  AZURE_DATABASE: "migration_demo"
  AZURE_USER: "azureadmin"
  AZURE_REGION: "Central US"
  AZURE_SKU: "Standard_B1ms"
  AZURE_TIER: "Burstable"
  AZURE_VERSION: "17"
  AZURE_STORAGE: "32"
  RESOURCE_GROUP_DB: "rg-raghav430reddy-2688"
  LOCAL_HOST: "migration-demo-raghava-20251006164232.postgres.database.azure.com"
  LOCAL_USER: "azureadmin"
  EXPORT_FILE: "migration_backup.sql"
  PROJECT_DIR: "."
  REUSE_EXISTING: "true"
  AZURE_AI_PROJECT_ENDPOINT: "https://raghavareddy-8243-resource.services.ai.azure.com/api/projects/raghavareddy-8243"
  AZURE_AI_MODEL_DEPLOYMENT_NAME: "gpt-4o"
